import Head from 'next/head'
import useRequest from "@/hooks/useRequest";
import {useEffect} from "react";
import {ApiRoutes} from "@/enums/ApiRoutes";
import CountryItem from "@/components/countryItem";

export type CountriesDataType = {
  name: { official: string }
  capital:string[]
  region:string
  population:number
  flags: { png:string,svg:string,alt:string }
}
type ResponseType = {
  data: Array<CountriesDataType>
}
export default function Home() {
  const [fetchCountries, countriesRes] = useRequest()
  const countries = countriesRes?.data as Array<CountriesDataType>

  useEffect(() => {
    fetchCountries({url: ApiRoutes.FETCH_COUNTRIES})
  }, [])

  return (
      <>
        <Head>
          <title>Country App </title>
          <meta name="description" content="Generated by create next app"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div className=" grid lg:grid-cols-4 gap-20 container mx-auto py-20">
          {
            countries?.length > 0 ?
                countries.map((item, index) => (
                    <CountryItem key={"COUNTRY_ITEM" + index}
                                 name={item.name.official}
                                 flag={item.flags}
                                 population={item.population}
                                 region={item.region}
                                 capital={item.capital}
                    />
                ))
                :
                <h1>LOADINg</h1>
          }
        </div>
      </>
  )
}

// export async function getServerSideProps(context) {
//   const res = await fetch("https://restcountries.com/v3.1/all")
//   const data = await res.json()
//   return {
//     props: {
//       countries:data
//     }, // will be passed to the page component as props
//   }
// }
